### ISSUE TITLE
Is this still usable

### ISSUE THREAD

**Issue by chrisdmacrae** [reclaim-the-stack/actioncable-enhanced-postgresql-adapter#1]
I'd really like to get redis out of my stack.

I saw your Reddit post and the PR to Rails. But no commits for 6 months. Is that because this is stable or because it's not being maintained?

@dbackeus thanks for you work either way!

**Comment by dbackeus** [comment]
Because it's stable.

Note that the base postgres adapter in rails hasn't had any meaningful commits since 2016 or so.

**Comment by chrisdmacrae** [comment]
@dbackeus you're the MVP my man
